spring:
  profiles:
    active: ${module}
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

server:
  port: ${port:8080}

aws:
  access-key-id: ${ACCESS_KEY_ID}
  secret-access-key: ${SECRET_ACCESS_KEY}
  session-token: ${AWS_SESSION_TOKEN}
  region: "us-east-1"

topics:
  payments-queue:
    url: "https://sqs.us-east-1.amazonaws.com/764385045273/orders-inventory-queue"
    delay: 100
  inventory-queue:
    url: "https://sqs.us-east-1.amazonaws.com/764385045273/orders-inventory-queue"
    delay: 100
