name: CICD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build
        
      - name: Login to docker hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
        
      - name: Build docker image
        run: docker build -t joubina1/marketplacebackcointainer .
        
      - name: Publish image to docker hub
        run: docker push joubina1/marketplacebackcointainer:latest


  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Delete old container
        run: sudo docker rm -f marketplacebackcointainer

      - name: Remove old image
        run: sudo docker image prune -a -f

      - name: Pull Image from docker hub
        run: sudo docker pull joubina1/marketplacebackcointainer:latest

      - name: Run Docker Container
        env:
            SECURITY_KEY: ${{ secrets.SECURITY_KEY }}
            AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
            AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
        run: |
            sudo docker run -d -p 8080:8080 --name marketplacebackcointainer \
            -e DATABASE_URL="${{ secrets.DATABASE_URL }}" -e CLOUDINARY_URL="${{ secrets.CLOUDINARY_URL }}" -e SECURITY_KEY="${{ secrets.SECURITY_KEY }}" -e AWS_SECRET_KEY="${{ secrets.AWS_SECRET_KEY }}" -e AWS_ACCESS_KEY="${{ secrets.AWS_ACCESS_KEY }}" \
            joubina1/marketplacebackcointainer

