name: CICD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test
        
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Build docker Orders image
        run: docker build -t joubina1/marketplacebackorderscointainer .
      - name: Build docker Payments image
        run: docker build -t joubina1/marketplacebackpaymentscointainer .
      - name: Build docker Inventory image
        run: docker build -t joubina1/marketplacebackinventorycointainer .
        
      - name: Publish Orders image to Docker Hub
        run: docker push joubina1/marketplacebackorderscointainer:latest
      - name: Publish Payments image to Docker Hub
        run: docker push joubina1/marketplacebackpaymentscointainer:latest
      - name: Publish Inventory image to Docker Hub
        run: docker push joubina1/marketplacebackinventorycointainer:latest

  deploy-orders:
    needs: build
    runs-on: [self-hosted, orders]
    steps:
      - name: Delete old Orders container
        run: sudo docker rm -f marketplacebackorderscointainer || true

      - name: Remove old image
        run: sudo docker image prune -a -f

      - name: Pull Orders Image from Docker Hub
        run: sudo docker pull joubina1/marketplacebackorderscointainer:latest

      - name: Run Docker Orders Container
        run: |
          sudo docker run -d -p 8080:8080 --name marketplacebackorderscointainer \
          -e SECURITY_KEY="IQoJb3JpZ2luX2VjEL3//////////wEaCXVzLXdlc3QtMiJHMEUCIQDBAZAMc8oUPF3osB6HP/s0UotSLFxXJt3ZSq4+boj6fQIgM/02V47wBncpX7qodrmquEcbQJ9jvNqzanQtbrooqEkqqAIIZhABGgw3NjQzODUwNDUyNzMiDHKugAEb2/u7KVL4ayqFAh0qcHFife9Oq6iU2H4QBtYa4XwGMmG1gRd6WKl6BYASHjkWf96x1mVy2zGvKt+UoUmbSayEk0kVBtAxT4WR5za8WqQcu9pcpb/xDbPpQCdkoaoLsimQkh+O66nQf4eQC4JWXFMEv8xN0JDUpeBODFwENUaAGJkfOeupp5gak1ZGvAo515LtFfVR6UJQ9+hbgIyCPPHdmYmjzZVAzQA4uTN2LXG9ABqan/uPWKcK4VY4MFXM76xHpCMLmBaIO4X2il3syc23pYWr+Q2syYIXoWVHKT/gwJKX8/xBPKbQS8vXo/6igS8jMMwCPf0fuvWpVLWN+4qUPuBltbwQKVPpnqoUTBHPUTDmme/ABjqdAVoiEV108ZJIUfHlYeZ2YzfME88pVStGCljF/IEdYSTPL/gUH2et4f3ajPs+4blzPf/G4O//uCG8IwfZId7cVv3s+r7qTQAenFufVxCoZXVhCYymObKUjsPPcZ/y+CQJDo6hu5vaGwzdAdkhV4d9ftkC1yj5as5QMI7bnw7uTa03XCtuH1Pa6cPn+RYBG17qIUTNcokEt/OzM+cQZBc=" \
          -e AWS_SECRET_KEY="tK4kBr4Xrq+EriyqxHW72wo5qFmSz1oV5IMxiSKu" \
          -e AWS_ACCESS_KEY="ASIA3D6HGFMM4LBTYT2Y" \
          -e module="orders" \
          joubina1/marketplacebackorderscointainer

  deploy-payments:
    needs: build
    runs-on: [self-hosted, payments]
    steps:
      - name: Delete old Payments container
        run: sudo docker rm -f marketplacebackpaymentscointainer || true

      - name: Remove old image
        run: sudo docker image prune -a -f

      - name: Pull Payments Image from Docker Hub
        run: sudo docker pull joubina1/marketplacebackpaymentscointainer:latest

      - name: Run Docker Payments Container
        run: |
          sudo docker run -d -p 8080:8080 --name marketplacebackpaymentscointainer \
          -e SECURITY_KEY="IQoJb3JpZ2luX2VjEL3//////////wEaCXVzLXdlc3QtMiJHMEUCIQDBAZAMc8oUPF3osB6HP/s0UotSLFxXJt3ZSq4+boj6fQIgM/02V47wBncpX7qodrmquEcbQJ9jvNqzanQtbrooqEkqqAIIZhABGgw3NjQzODUwNDUyNzMiDHKugAEb2/u7KVL4ayqFAh0qcHFife9Oq6iU2H4QBtYa4XwGMmG1gRd6WKl6BYASHjkWf96x1mVy2zGvKt+UoUmbSayEk0kVBtAxT4WR5za8WqQcu9pcpb/xDbPpQCdkoaoLsimQkh+O66nQf4eQC4JWXFMEv8xN0JDUpeBODFwENUaAGJkfOeupp5gak1ZGvAo515LtFfVR6UJQ9+hbgIyCPPHdmYmjzZVAzQA4uTN2LXG9ABqan/uPWKcK4VY4MFXM76xHpCMLmBaIO4X2il3syc23pYWr+Q2syYIXoWVHKT/gwJKX8/xBPKbQS8vXo/6igS8jMMwCPf0fuvWpVLWN+4qUPuBltbwQKVPpnqoUTBHPUTDmme/ABjqdAVoiEV108ZJIUfHlYeZ2YzfME88pVStGCljF/IEdYSTPL/gUH2et4f3ajPs+4blzPf/G4O//uCG8IwfZId7cVv3s+r7qTQAenFufVxCoZXVhCYymObKUjsPPcZ/y+CQJDo6hu5vaGwzdAdkhV4d9ftkC1yj5as5QMI7bnw7uTa03XCtuH1Pa6cPn+RYBG17qIUTNcokEt/OzM+cQZBc=" \
          -e AWS_SECRET_KEY="tK4kBr4Xrq+EriyqxHW72wo5qFmSz1oV5IMxiSKu" \
          -e AWS_ACCESS_KEY="ASIA3D6HGFMM4LBTYT2Y" \
          -e module="payments" \
          joubina1/marketplacebackpaymentscointainer

  deploy-inventory:
    needs: build
    runs-on: [self-hosted, inventory]
    steps:
      - name: Delete old Inventory container
        run: sudo docker rm -f marketplacebackinventorycointainer || true

      - name: Remove old image
        run: sudo docker image prune -a -f

      - name: Pull Inventory Image from Docker Hub
        run: sudo docker pull joubina1/marketplacebackinventorycointainer:latest

      - name: Run Docker Inventory Container
        run: |
          sudo docker run -d -p 8080:8080 --name marketplacebackinventorycointainer \
          -e SECURITY_KEY="IQoJb3JpZ2luX2VjEL3//////////wEaCXVzLXdlc3QtMiJHMEUCIQDBAZAMc8oUPF3osB6HP/s0UotSLFxXJt3ZSq4+boj6fQIgM/02V47wBncpX7qodrmquEcbQJ9jvNqzanQtbrooqEkqqAIIZhABGgw3NjQzODUwNDUyNzMiDHKugAEb2/u7KVL4ayqFAh0qcHFife9Oq6iU2H4QBtYa4XwGMmG1gRd6WKl6BYASHjkWf96x1mVy2zGvKt+UoUmbSayEk0kVBtAxT4WR5za8WqQcu9pcpb/xDbPpQCdkoaoLsimQkh+O66nQf4eQC4JWXFMEv8xN0JDUpeBODFwENUaAGJkfOeupp5gak1ZGvAo515LtFfVR6UJQ9+hbgIyCPPHdmYmjzZVAzQA4uTN2LXG9ABqan/uPWKcK4VY4MFXM76xHpCMLmBaIO4X2il3syc23pYWr+Q2syYIXoWVHKT/gwJKX8/xBPKbQS8vXo/6igS8jMMwCPf0fuvWpVLWN+4qUPuBltbwQKVPpnqoUTBHPUTDmme/ABjqdAVoiEV108ZJIUfHlYeZ2YzfME88pVStGCljF/IEdYSTPL/gUH2et4f3ajPs+4blzPf/G4O//uCG8IwfZId7cVv3s+r7qTQAenFufVxCoZXVhCYymObKUjsPPcZ/y+CQJDo6hu5vaGwzdAdkhV4d9ftkC1yj5as5QMI7bnw7uTa03XCtuH1Pa6cPn+RYBG17qIUTNcokEt/OzM+cQZBc=" \
          -e AWS_SECRET_KEY="tK4kBr4Xrq+EriyqxHW72wo5qFmSz1oV5IMxiSKu" \
          -e AWS_ACCESS_KEY="ASIA3D6HGFMM4LBTYT2Y" \
          -e module="inventory" \
          joubina1/marketplacebackinventorycointainer
